[tool.poetry]
authors = ["Lunarmagpie <Bambolambo0@gmail.com>"]
description = "The TagScript Bot"
license = "MIT"
name = "bot"
version = "0.1.0"

[tool.poetry.dependencies]
hikari = "^2.0.0-alpha.108"
hikari-crescent = "^0.1.0"
python = ">=3.8,<3.11"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.960"
nox = "^2022.1.7"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
line-length=88
skip-magic-trailing-comma=true
target-version=['py38']
