CREATE TABLE guilds ();
CREATE TABLE scripts ();
CREATE TABLE event_triggers ();
CREATE TABLE event_trigger_scripts ();
CREATE TABLE _migrations ();
ALTER TABLE guilds ADD COLUMN guild_id NUMERIC;
ALTER TABLE guilds ADD COLUMN log_channel NUMERIC;
ALTER TABLE scripts ADD COLUMN script_id SERIAL;
ALTER TABLE scripts ADD COLUMN guild_id NUMERIC;
ALTER TABLE scripts ADD COLUMN name TEXT;
ALTER TABLE scripts ADD COLUMN code TEXT;
ALTER TABLE event_triggers ADD COLUMN trigger_id SERIAL;
ALTER TABLE event_triggers ADD COLUMN guild_id NUMERIC;
ALTER TABLE event_triggers ADD COLUMN event_type SMALLINT;
ALTER TABLE event_trigger_scripts ADD COLUMN trigger_id INTEGER;
ALTER TABLE event_trigger_scripts ADD COLUMN script_id INTEGER;
ALTER TABLE _migrations ADD COLUMN id_ INTEGER;
ALTER TABLE guilds ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE scripts ALTER COLUMN script_id SET NOT NULL;
ALTER TABLE scripts ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE scripts ALTER COLUMN name SET NOT NULL;
ALTER TABLE scripts ALTER COLUMN code SET NOT NULL;
ALTER TABLE event_triggers ALTER COLUMN trigger_id SET NOT NULL;
ALTER TABLE event_triggers ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE event_triggers ALTER COLUMN event_type SET NOT NULL;
ALTER TABLE event_trigger_scripts ALTER COLUMN trigger_id SET NOT NULL;
ALTER TABLE event_trigger_scripts ALTER COLUMN script_id SET NOT NULL;
ALTER TABLE _migrations ALTER COLUMN id_ SET NOT NULL;
CREATE INDEX _hash_index_scripts__guild_id ON scripts USING HASH ( ( guild_id ) );
CREATE INDEX _hash_index_scripts__name ON scripts USING HASH ( ( name ) );
CREATE INDEX _hash_index_event_triggers__guild_id ON event_triggers USING HASH ( ( guild_id ) );
CREATE INDEX _hash_index_event_triggers__event_type ON event_triggers USING HASH ( ( event_type ) );
ALTER TABLE scripts ADD CONSTRAINT guild_name_unique UNIQUE ( name , guild_id );
ALTER TABLE event_triggers ADD CONSTRAINT guild_event_unique UNIQUE ( guild_id , event_type );
ALTER TABLE guilds ADD CONSTRAINT _guilds_guild_id_primary_key PRIMARY KEY ( guild_id );
ALTER TABLE scripts ADD CONSTRAINT _scripts_script_id_primary_key PRIMARY KEY ( script_id );
ALTER TABLE event_triggers ADD CONSTRAINT _event_triggers_trigger_id_primary_key PRIMARY KEY ( trigger_id );
ALTER TABLE event_trigger_scripts ADD CONSTRAINT _event_trigger_scripts_trigger_id_script_id_primary_key PRIMARY KEY ( trigger_id , script_id );
ALTER TABLE _migrations ADD CONSTRAINT __migrations_id__primary_key PRIMARY KEY ( id_ );
ALTER TABLE scripts ADD CONSTRAINT guild_fk FOREIGN KEY ( guild_id ) REFERENCES guilds ( guild_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE event_trigger_scripts ADD CONSTRAINT trigger_fk FOREIGN KEY ( trigger_id ) REFERENCES event_triggers ( trigger_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE event_trigger_scripts ADD CONSTRAINT script_fk FOREIGN KEY ( script_id ) REFERENCES scripts ( script_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;